name: "rohitmukherjee.com"
description: "Rohit Mukherjee's Website"

url: "http://localhost:4000"
#url: "http://rohitmukherjee.com"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments