name: "rohitmukherjee.com"
description: "Rohit Mukherjee's Website"

#url: "http://rohitmukherjee.com"
url: "http://rohitmukherjee.github.io"
paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: rouge
